name: front-end build and lint

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1.1.0

    - name: Setup cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run elm
      run: |
        npx elm make src/NoEmptyText.elm --output /dev/null

    - name: Elm-analyse
      run: |
        npx elm-analyse

    - name: run tests
      run: |
        npm i elm
        npx elm-test

